import type { Metadata } from "next";
import Header from "../components/header/Header";
import Sidebar from "../components/sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen flex flex-col">
      {/* ヘッダー */}
      <Header />

      {/* メインエリア */}
      <div className="flex flex-1 overflow-hidden">
        {/* サイドバー */}
        <Sidebar />

        {/* コンテンツ */}
        <div className="flex-1 bg-gray-200 overflow-auto p-4">{children}</div>
      </div>
    </div>
  );
}
