import type { Metadata } from "next";
import ChannelSidebar from "../../components/channelSidebar/ChannelSidebar";
import Header from "../../components/header/Header";
import ServerSidebar from "../../components/serverSidebar/ServerSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen flex flex-col">
      {/* ヘッダー */}
      <Header />

      {/* メインエリア */}
      <div className="flex flex-2 overflow-hidden">
        {/* サイドバー */}
        <ServerSidebar />
        <ChannelSidebar />

        {/* コンテンツ */}
        <div className="flex-1 bg-gray-200 overflow-auto p-4">{children}</div>
      </div>
    </div>
  );
}
